### ISSUE TITLE
The Script Just Doesn't Work

### ISSUE THREAD

**Issue by luhgarlicbread** [e9x/chrome-versions#2]
Yo so I tried following the instructions provided andddd:
"ethan@ethan-zorinos-linux:~/chrome-versions$ npm run init

> chrome-versions@1.0.4 init /home/ethan/chrome-versions
> node --loader=ts-node/esm scripts/initDatabase.ts

node: --loader requires --experimental-modules be enabled"

Okay. So I ran:
"> ethan@ethan-zorinos-linux:~/chrome-versions$ node --experimental-modules run init
(node:5411) ExperimentalWarning: The ESM module loader is experimental.
{ Error: Cannot find module /home/ethan/chrome-versions/run
    at search (internal/modules/esm/default_resolve.js:29:12)
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:65:11)
    at Loader.resolve (internal/modules/esm/loader.js:58:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:113:40)
    at Loader.import (internal/modules/esm/loader.js:99:28)
    at asyncESM.loaderPromise.then (internal/modules/cjs/loader.js:823:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3) code: 'MODULE_NOT_FOUND' }"

Nothing.

[log.txt](https://github.com/e9x/chrome-versions/files/14859872/log.txt)

**Comment by luhgarlicbread** [comment]
NVM! I got it to work on WSL instead of booting bare linux.

**Comment by e9x** [comment]
with vite-node, there shouldn't be any crap about experimental modules. ts-node sucks.

**Comment by luhgarlicbread** [comment]
> with vite-node, there shouldn't be any crap about experimental modules. ts-node sucks.

that's what's up
